application:
    build: docker/code
    volumes:
        - ./WellFollowed:/var/www/wellfollowed:rw
        - ./docker/logs/wellfollowed:/var/www/wellfollowed/app/logs:rw
    tty: true
db:
    image: mariadb
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: wellfollowed
        MYSQL_USER: wellfollowed
        MYSQL_PASSWORD: wellfollowed
php:
    build: docker/php-fpm
    ports:
        - 9000:9000
    volumes_from:
        - application
    links:
        - db
#xdebug:
#    build: xdebug
#    environment:
#        XDEBUG_CONFIG: remote_host=192.168.1.14
nginx:
    build: docker/nginx
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - application
    volumes:
        - ./docker/logs/nginx/:/var/log/nginx
rabbitmq:
    image: rabbitmq
    ports:
        - 8081:15672