well_followed_api:
    resource: "@WellFollowedAppBundle/Controller/Api/"
    type:     annotation
    prefix: /api

well_followed_web:
    resource: "@WellFollowedAppBundle/Controller/Web/"
    type: annotation
    prefix: /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"