# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
parameters:
    oauth2_scopes:
        access_home: "Accéder à la page d'acceuil"
        access_sensor: "Lire les données capteurs"
        access_admin: "Accéder à la partie administration du site"
        access_calendar: "Accéder au calendrier"
        access_user: "Accéder aux utilisateurs"
        access_token_user: "Autoriser l'utilisateur courant"
    oauth2_clients:
        well_followed_web:
            redirect_uris: ["http://localhost:8085"]
            description: "Application web WellFollowed."
            grant_types: ["password"]
            scopes: ["access_home", "access_sensor", "access_admin"]
            default_scopes: ["access_home"]

security:
    encoders:
        WellFollowed\OAuth2\ServerBundle\Entity\User:
            algorithm:          sha512
            encode_as_base64:   true
            iterations:         5000


    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        oauth2:
            id: oauth2.user_provider
        # in_memory:
#            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #api:
        #    pattern: ^/api/
        #    form_login:
        #        provider: oauth2
        #        login_path: /#/login
        #        check_path: token
        #    stateless: true

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
