# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
parameters:
    oauth2_scopes:
        readsensor: "Lire les données capteurs"
        readadmin: "Accéder à la partie administration du site"
    oauth2_public_clients:
        user: ["readsensor"]
        admin: ["readsensor", "readadmin"]

security:
    encoders:
        OAuth2\ServerBundle\Entity\User:
            algorithm:          sha512
            encode_as_base64:   true
            iterations:         5000


    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        oauth2:
            id: oauth2.user_provider
        # in_memory:
#            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
