# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    # Listeners

    well_followed.exception_listener:
        class: WellFollowedBundle\EventListener\ExceptionListener
        arguments: ["@jms_serializer", "%kernel.environment%"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    well_followed.tokens.action_listener:
        class: WellFollowedBundle\EventListener\TokenListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    # Services

    well_followed.user_service:
        class: WellFollowedBundle\Service\UserService
        arguments: ["@oauth2.user_provider", "@doctrine.orm.entity_manager", "@oauth2.client_manager", "@oauth2.grant_type.user_credentials", "@oauth2.scope_manager"]

    well_followed.client_service:
        class: WellFollowedBundle\Service\ClientService
        arguments: ["@doctrine.orm.entity_manager", "@oauth2.scope_manager", "@oauth2.client_manager"]