# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

    # Repositories


    # Managers

#    well_followed.event_manager.class: WellFollowedBundle\Manager\EventManager
#    well_followed.user_manager.class: WellFollowedBundle\Manager\UserManager
#    well_followed.client_manager.class: WellFollowedBundle\Manager\ClientManager

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    # Listeners

    well_followed.exception_listener:
        class: WellFollowedBundle\EventListener\ExceptionListener
        arguments: ["@jms_serializer", "%kernel.environment%"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    well_followed.tokens.action_listener:
        class: WellFollowedBundle\EventListener\TokenListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    # Repositories


    # Managers

#    well_followed.event_manager:
#        class: "%well_followed.event_manager.class%"
#        arguments: ["@well_followed.event_repository"]
#
#    well_followed.user_manager:
#        class: "%well_followed.user_manager.class%"
#        arguments: ["@oauth2.user_provider", "@doctrine.orm.entity_manager", "@oauth2.client_manager", "@oauth2.grant_type.user_credentials", "@oauth2.scope_manager"]
#
#    well_followed.client_manager:
#        class: "%well_followed.client_manager.class%"
#        arguments: ["@doctrine.orm.entity_manager", "@oauth2.scope_manager", "@oauth2.client_manager"]