# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    # Util
    util.cache.class: Doctrine\Common\Cache\ApcCache
    util.metadata_factory.class: Metadata\MetadataFactory
    util.metadata.controller_annotation_driver.class: WellFollowed\UtilBundle\Metadata\Driver\ControllerAnnotationDriver
    util.processor.controller_annotation_processor.class: WellFollowed\UtilBundle\Processor\ControllerAnnotationProcessor
    util.event_listener.controller_listener.class: WellFollowed\UtilBundle\EventListener\ControllerListener

    # WellFollowed
    well_followed.exception_listener.class: WellFollowed\AppBundle\EventListener\ExceptionListener
    well_followed.tokens.action_listener.class: WellFollowed\AppBundle\EventListener\TokenListener

    # OAuth2 overrides
    oauth2.user_provider.class: WellFollowed\OAuth2\ServerBundle\User\OAuth2UserProvider
    oauth2.client_manager.class: WellFollowed\OAuth2\ServerBundle\Manager\ClientManager


    # Repositories


    # Managers

#    well_followed.event_manager.class: WellFollowed\AppBundle\Manager\EventManager
#    well_followed.user_manager.class: WellFollowed\AppBundle\Manager\UserManager
#    well_followed.client_manager.class: WellFollowed\AppBundle\Manager\ClientManager

services:
    # Util
#    util.cache:
#        class: "%util.cache.class%"
#
#    util.metadata.controller_annotation_driver:
#        class: "%util.metadata.controller_annotation_driver.class%"
#        arguments: ["@annotation_reader"]
#
#    util.metadata_factory:
#        class: "%util.metadata_factory.class%"
#        arguments: ["@util.metadata.controller_annotation_driver"]
#
#    util.processor.controller_annotation_processor:
#        class: "%util.processor.controller_annotation_processor.class%"
#        arguments: ["@util.metadata_factory", "@jms_serializer"]
#
#    util.event_listener.controller_listener:
#        class: "%util.event_listener.controller_listener.class%"
#        arguments: ["@util.processor.controller_annotation_processor"]
#        tags:
#            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
#            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    # Listeners

    well_followed.exception_listener:
        class: "%well_followed.exception_listener.class%"
        arguments: ["@jms_serializer", "%kernel.environment%"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

#    well_followed.tokens.action_listener:
#        class: "%well_followed.tokens.action_listener.class%"
#        tags:
#            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    # Repositories


    # Managers

#    well_followed.event_manager:
#        class: "%well_followed.event_manager.class%"
#        arguments: ["@well_followed.event_repository"]
#
#    well_followed.user_manager:
#        class: "%well_followed.user_manager.class%"
#        arguments: ["@oauth2.user_provider", "@doctrine.orm.entity_manager", "@oauth2.client_manager", "@oauth2.grant_type.user_credentials", "@oauth2.scope_manager"]
#
#    well_followed.client_manager:
#        class: "%well_followed.client_manager.class%"
#        arguments: ["@doctrine.orm.entity_manager", "@oauth2.scope_manager", "@oauth2.client_manager"]