wellfollowed_sensor_topic:
    channel: sensor/data/{sensorName}
    handler:
        callback: 'well_followed.recording.sensor'
    requirements:
        sensorName:
            pattern: "[a-zA-Z0-9]+"