<?php

namespace WellFollowedBundle\Entity;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEvents($criteria = null) {
        if (!is_null($criteria)) {
            return $this->findBy($criteria);
        }
        return $this->findAll();
    }
}
