<?php

namespace WellFollowedBundle\Entity;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEvents($filter = null) {
        if (!is_null($filter)) {
            return $this->findBy($filter);
        }
        return $this->findAll();
    }

    public function createEvent(Event $event) {
        $entityManager = $this->getEntityManager();

        $event->setStart(new \DateTime());
        $event->setEnd(new \DateTime());
        $event->setName("ok");

        $entityManager->persist($event);
        $entityManager->flush();

        return $event;
    }
}
