<?php

namespace WellFollowedBundle\Entity;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEvents(array $filter = null) {
        if (!is_null($filter)) {
            $qb = $this->createQueryBuilder('e');

            // We take into account the end of the first event matched and the end of the last one
            // in order to be consistent.
            if (!is_null($filter['start']))
                $qb->andWhere('e.end > :start')
                    ->setParameter('start', $filter['start']);
            if (!is_null($filter['end']))
                $qb->andWhere('e.end < :end')
                    ->setParameter('end', $filter['end']);

            return $qb->getQuery()
                ->getResult();
        }
        return $this->findAll();
    }

    public function createEvent(Event $event) {
        $em = $this->getEntityManager();

        $em->persist($event);
        $em->flush();

        return $event;
    }

    public function deleteEvent($id) {
        $id = (int) $id;

        if ($id > 0) {
            $qb = $this->createQueryBuilder('e');

            $qb->delete('WellFollowedBundle\Entity\Event', 'e')
                ->where('e.id = :id')
                ->setParameter('id', $id);

            return $qb->getQuery()
                ->execute();
        }

        throw new NotFoundHttpException();
    }
}
