<?php

namespace WellFollowedBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUsers(array $criteria = null) {
        if (!is_null($criteria)) {
            return $this->findBy($criteria);
        }
        return $this->findAll();
    }

    public function createUser(User $user) {
        $entityManager = $this->getEntityManager();

        $entityManager->persist($user);
        $entityManager->flush();

        return $user;
    }
}
