<?php

namespace WellFollowedBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUsers(array $criteria = null) {
        if (!is_null($criteria)) {
            return $this->findBy($criteria);
        }
        return $this->findAll();
    }
}
